import React, { useState, useEffect } from "react";
import ExportedImage from "next-image-export-optimizer";
import Link from "next/link";
import styles from "./use-case.module.css";
import Head from "next/head";

import Header from "../header";
import FooterVersionSecond from "../footerv2";
import Layout from "./layout";

export default function HandlingLargeDataVolumesAutomotive(props: any) {
  const data = {
    title: "Handling Large Data Volumes in Automotive",
    logo: "sgAnalytics.png",
    contentImage: "case2.png",
    info_1:
      "An automotive manufacturer faced challenges in managing and leveraging vast amounts of data generated by sensors embedded in vehicles and manufacturing equipment. The existing systems struggled to handle high-velocity data streams effectively, hindering real-time analytics and decision-making processes.",
    info_2: "",
    info_3: "",
    boxedInfo: [],
    points: [
      {
        title: "Challenges",
        desc: "",
        desc2: "",
        listItems: [
          {
            title: "IHigh-Volume Data Streams:",
            text: "Managing data from thousands of sensors across vehicles and manufacturing equipment.",
          },
          {
            title: "Real-Time Data Processing: ",
            text: "Inability to process and analyze data in real time for timely insights and decision-making.",
          },
          {
            title: "Centralized Data Management: ",
            text: "Lack of a centralized platform for integrating and storing large volumes of diverse data types.",
          },
        ],
      },
      {
        title: "Real-Time Data Integration",
        desc: "Streamlined data processing from multiple sources for real-time insights.",
        desc2: "",
        listItems: [],
      },
      {
        title: "Predictive Maintenance",
        desc: "Utilized ML models to forecast equipment failures and reduce downtime.",
        desc2: "",
        listItems: [],
      },
      {
        title: "Custom Dashboards",
        desc: "Enhanced decision-making through tailored visualizations and reports.",
        desc2: "",
        listItems: [],
      },
      {
        title: "Scalable Data Warehousing",
        desc: "Managed large data volumes efficiently with robust architecture.",
        desc2: "",
        listItems: [],
      },
      {
        title: "Impact",
        desc: "",
        desc2: "",
        listItems: [
          {
            title: "Enhanced Product Quality",
            text: "By analyzing data from vehicle sensors and customer feedback, the company identified and addressed common defects, leading to a 15% reduction in warranty claims.",
          },
          {
            title: "Operational Efficiency:",
            text: "Real-time monitoring and predictive maintenance reduced equipment downtime by 20%, leading to significant cost savings and improved production efficiency. The ability to proactively address issues before they resulted in failures minimized disruptions.",
          },
          {
            title: "Data-Driven Decision Making:",
            text: "Custom dashboards and advanced analytics empowered employees at all levels to make data-driven decisions. This capability resulted in faster response times to operational issues and more informed strategic planning.",
          },
          {
            title: "Cost Savings:",
            text: "Efficient data management and analytics processes led to a 25% reduction in operational costs. Optimizing the supply chain and reducing waste contributed to these savings, enhancing the company's overall profitability.",
          },
        ],
      },
    ],
  };
  return (
    <>
      <Head>
        <title>Shodat AI Platform | Use Cases</title>
        <meta name="title" content="Shodat AI Platform | Use Cases" />
        <meta
          name="description"
          content="Explore the powerful Shodat AI platform eOps, offering advanced AI solutions to meet the unique needs of your industry."
        />
        <meta
          name="keywords"
          content="AI platform Shodat eOps Advanced analyticsData integrationScalable solutions"
        />
        <meta name="robots" content="index, follow" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="English" />
      </Head>

      <div className="useCases">
        {/* -- Header -- */}
        <Header />

        <div className={`${styles.useCasesWrapper}`}>
          <Layout pageData={data} />
        </div>

        {/* Footer */}
        <FooterVersionSecond />
      </div>
    </>
  );
}
